### ISSUE TITLE
Invalid torrent identifier bug

### ISSUE THREAD

**Issue by gyzerok** [feross/parse-torrent#10]
I'm always getting this exception while trying to parse torrent file using:
```javascript
parseTorrent(fs.readFileSync(path))
```
It seems to me files are ok since BitTorrent handles them correctly.
Dunno if its ok to give you link here.

**Comment by gyzerok** [comment]
The problem here is that Buffer.isBuffer returns false on result of fs.readFileSync. Solution:
```javascript
parseTorrent(new Buffer(fs.readFileSync(path, { encoding: 'utf8' })))
```

But after this I'm getting exception ```Invalid data: Missing delimiter ":" [0x3a]``` from parse-torrent-file module.

**Comment by feross** [comment]
I think there's some other major issue with your code. `Buffer.isBuffer(fs.readFileSync(pathToFile))` always returns `true`, unless there's some edge case I'm not aware of.

If you can't figure it out, email me the file you think isn't working (email is on my profile).

**Comment by aurimus** [comment]
Had the same problem, @feross is right - the problem is in the command - you have to leave out utf8 cause .torrent file is not a entirely text.
